#!/usr/bin/env bash
# Run Nginx as Nginx
sudo sed -1 's/user www-data/user nginx' /etc/nginx/nginx.config
sudo sed -1 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.config
sudo -u nginx service nginx restart
